### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [PYLiao/splurtyPY#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by PYLiao** [comment]
Hi Ken!
I have add a line in the <head> in 'application.html.erb'; which is

<meta name="viewport" content="width=device-width">

then the font size on mobile seems larger.

**Comment by PYLiao** [comment]
the line did not show up...

I mean add a line in "<head>":

"<meta name="viewport" content="width=device-width">"

**Comment by PYLiao** [comment]
sorry....that's weird..
How about this

meta name="viewport" content="width=device-width"

**Comment by kenmazaika** [comment]
Thumbs up.  Looks great! :)
